### ISSUE TITLE
这是一个悲剧

### ISSUE THREAD

**Issue by Ningersan** [v-cynosure/X-Files#1]
本来只是想测试一下issue怎么用的
结果发现删不掉了
我被永久的定在历史的耻辱柱上
T T
然后我发现每次的修改记录也被存上了
还删除不了
算了 大家就当我是精分吧
我再也不想用issue这个功能了
没救了 治不了 告辞

**Comment by VickieYan** [comment]
hhhhhhhhh
Jason你太蠢了
